// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Image analysis AI agent.
 *
 * - analyzeImage - A function that handles the image analysis process.
 * - AnalyzeImageInput - The input type for the analyzeImage function.
 * - AnalyzeImageOutput - The return type for the analyzeImage function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeImageInputSchema = z.object({
  photoDataUri: z
    .string()
    .describe(
      "A photo to analyze, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type AnalyzeImageInput = z.infer<typeof AnalyzeImageInputSchema>;

const AnalyzeImageOutputSchema = z.object({
  objects: z.array(z.string()).describe('List of objects detected in the image.'),
  theme: z.string().describe('Overall theme or context of the image.'),
  description: z.string().describe('A concise description of the image.'),
});
export type AnalyzeImageOutput = z.infer<typeof AnalyzeImageOutputSchema>;

export async function analyzeImage(input: AnalyzeImageInput): Promise<AnalyzeImageOutput> {
  return analyzeImageFlow(input);
}

const analyzeImagePrompt = ai.definePrompt({
  name: 'analyzeImagePrompt',
  input: {schema: AnalyzeImageInputSchema},
  output: {schema: AnalyzeImageOutputSchema},
  prompt: `You are an AI expert in image analysis. Analyze the image provided and extract key objects, themes, and a concise description.

Image: {{media url=photoDataUri}}

Objects: Identify and list the distinct objects present in the image.
Theme: Determine the overarching theme or context of the image (e.g., wedding, birthday, product promotion).
Description: Provide a brief, descriptive summary of the image.

Format your output as a JSON object with 'objects', 'theme', and 'description' fields.`, 
});

const analyzeImageFlow = ai.defineFlow(
  {
    name: 'analyzeImageFlow',
    inputSchema: AnalyzeImageInputSchema,
    outputSchema: AnalyzeImageOutputSchema,
  },
  async input => {
    const {output} = await analyzeImagePrompt(input);
    return output!;
  }
);
